name: "Sign"

on:
  schedule:
    - cron: '15 1 * * *'
  watch:
    types: [started]

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Sign'
        env:
          GLADOS_COOKIE_1:    ${{ secrets.GLADOS_COOKIE_1 }}
          GLADOS_COOKIE_2:    ${{ secrets.GLADOS_COOKIE_2 }}
          GLADOS_COOKIE_3:    ${{ secrets.GLADOS_COOKIE_3 }}
          V2EX_COOKIE:        ${{ secrets.V2EX_COOKIE }}
          STUDYGOLANG_COOKIE: ${{ secrets.STUDYGOLANG_COOKIE }}
          LD246_NAME:         ${{ secrets.LD246_NAME }}
          LD246_PASSWORD:     ${{ secrets.LD246_PASSWORD }}
          SCKEY:              ${{ secrets.SCKEY }}
        run: bash ./workflows
