name: "Sign"

on:
  schedule:
    - cron: '15 1 * * *'
  watch:
    types: [started]

jobs:
  sign:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Sign'
        env:
          SCKEY:              ${{ secrets.SCKEY }}
          LD246_NAME:         ${{ secrets.LD246_NAME }}
          LD246_PASSWORD:     ${{ secrets.LD246_PASSWORD }}
          V2EX_COOKIE:        ${{ secrets.V2EX_COOKIE }}
          STUDYGOLANG_COOKIE: ${{ secrets.STUDYGOLANG_COOKIE }}
          GLADOS_COOKIE_1:    ${{ secrets.GLADOS_COOKIE_1 }}
          GLADOS_COOKIE_2:    ${{ secrets.GLADOS_COOKIE_2 }}
          GLADOS_COOKIE_3:    ${{ secrets.GLADOS_COOKIE_3 }}
        run: go run sign.go
