name: "Sign"

on:
  schedule:
    - cron: '15 1 * * *'
  watch:
    types: [started]

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Sign v2ex'
        env:
          V2EX_COOKIE: ${{ secrets.V2EX_COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}
        run: bash ./v2ex.sh
      - name: 'Sign hacpai'
        env:
          HACPAI_COOKIE: ${{ secrets.HACPAI_COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}
        run: bash ./hacpai.sh
