name: "V2ex Sign"

on:
  push:
  schedule:
    - cron: '15 1 * * *'

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Sign v2ex'
        env:
          V2EX_COOKIE: ${{ secrets.V2EX_COOKIE }}
          SCKEY: ${{ secrets.SCKEY }}
        run: bash ./v2ex_sign.sh
